# Minimal ToolHive configuration
# Uses all defaults - deploys the ToolHive operator with standard settings
apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: ToolHive
metadata:
  name: toolhive
  namespace: example-env
spec:
  clusterName: my-cluster
